# Generated by Django 4.1.7 on 2023-03-08 20:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('email', models.CharField(max_length=100, verbose_name='email')),
                ('avatar', models.ImageField(upload_to='avatars/%Y/%m/%d')),
                ('designation', models.CharField(blank=True, max_length=100, verbose_name='designation')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='phone')),
                ('salary', models.PositiveIntegerField(blank=True, verbose_name='salary')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('date_hired', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
    ]
