# Generated by Django 4.1.7 on 2023-03-08 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='designation',
        ),
        migrations.AddField(
            model_name='employee',
            name='bio',
            field=models.CharField(blank=True, max_length=100, verbose_name='bio'),
        ),
    ]
